apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-fastapi
  labels:
    app: simple-fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-fastapi
  template:
    metadata:
      labels:
        app: simple-fastapi
    spec:
      containers:
        - name: app
          image: arezoumontazeri/simple-fastapi:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
               name: api-config
            - secretRef:
               name: api-secret
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /healthz
              port: 8000
            failureThreshold: 30
            periodSeconds: 2
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
