apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-fastapi
  labels:
    app: simple-fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-fastapi
  template:
    metadata:
      labels:
        app: simple-fastapi
    spec:
      containers:
        - name: app
          image: arezoumontazeri/simple-fastapi:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
               name: api-config
            - secretRef:
               name: api-secret
